### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/chronicle.rs#80]
## Description
This task will outline the requirements for implementing permanode on top of the new chronicle and scylla.

# Tasks

- [x] `chronicle` crate
  - [x] Start API, Broker, Scylla with launcher actor
- [x] `chronicle-storage` crate
  - [x] Implement keyspaces
  - [x] Implement scylla storage access
    - [x] Selects
    - [x] Inserts
    - [x] Deletes
- [x] `chronicle-api` crate
  - [x] Listener for Chrysalis Endpoints
    - [x] messages/${messageId}
    - [x] messages/${messageId}/metadata
    - [x] messages/${messageId}/children
    - [x] messages?index=${indexationKey}
    - [x] addresses/${bech32Address}/outputs
    - [x] outputs/${outputId}
    - [x] milestones/${index}
- [x] `chronicle-broker` crate
  - [x] Receive data from IOTA network
  - [x] Cache transactions in local tangle
  - [x] Persist transactions to scylla DB
  - [x] Connect to or remove MQTT peers
  - [x] Archive/Write ahead log milestones data #84  
  - [x] Solidifier iotaledger/permanode.rs#19 

- [ ] Dashboard (see #81, #82)
- [x] CLI #85
- [x] Notification and emergency alerts for administrators through email/msg
